import { Inter } from 'next/font/google';
import Providers from '@/context/providers';
import '../styles/main.scss';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Ammar Ecommerce',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      suppressContentEditableWarning={true}
      className="dark"
    >
      <body className={inter.className}>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
